---
- hosts: production_servers
  become: yes

  tasks:
    - name: Install MySQL
      apt: name={{ item }} state=latest update_cache=yes
      with_items:
        - python3-pymysql 
        - mysql-server
        - libmysqlclient-dev

    - name: Start the MySQL service
      action: service name=mysql state=started

#Так делать нельзя, но для теста можно
    - name: update mysql root password
      mysql_user:
        name: root
        password: 432qwe
        login_unix_socket: /var/run/mysqld/mysqld.sock
