---
- name: restart sshd
  service:
    name: sshd
    state: restarted

- name: save iptables
  community.general.iptables_state:
    ip_version: ipv4
    state: saved
    path: /etc/iptables/rules.v4
