---
- name: restart sshd
  service:
    name: "{{ 'ssh.socket' if ansible_distribution_version == '24.04' else 'sshd' }}"
    state: restarted

- name: save iptables
  community.general.iptables_state:
    ip_version: ipv4
    state: saved
    path: /etc/iptables/rules.v4
