---
# tasks file for ansible-dnsmasq
- name: install dependencies
  apt:
    name: dnsmasq
    state: latest
    update_cache: true
    cache_valid_time: 3600

- name: add specific configuration files
  template:
    src: etc/dnsmasq.d/config.j2
    dest: "/etc/dnsmasq.d/{{ item.key }}"
    owner: root
    group: root
    mode: 0644
    validate: 'dnsmasq --test -C %s'
  with_dict: "{{ dnsmasq_dnsmasq_d_files_present }}"
