---
- name: Copy backup script
  copy:
    src: backup.py
    dest: /opt/backup.py
    mode: "0755"

- name: Cron backup task in the first day of month
  cron:
    name: Backup job
    user: app
    month: "*"
    day: 1
    hour: 5
    minute: 0
    job: "python3 /opt/backup.py --source={{ backup_path }} --destination={{ dest_path }} 2>&1"
    disabled: false
    state: present
