---
ipfy_api_url: https://api.ipify.org/

percona_venv: /var/lib/mysql_backup/venv/

python_version: '3.8'

pip_packages:
  - boto
  - boto3
  - botocore
  - jmespath
  - python-dateutil
  - s3transfer
  - six
  - urllib3==1.26.20
  - python-dotenv

mysql_backup:
  retention: 5
  databases:
    - default
  aws_access_key: ''
  aws_secret_key: ''
  bucket_name: ''
  aws_region: ''
  s3_folder: ''
  path: /var/lib/mysql_backup
  hour: 1
  mysql_user: root
  mysql_password: ''
