---
- name: "Allow SSH {{ sshd_custom_port }}"
  iptables:
    action: insert
    chain: INPUT
    protocol: tcp
    destination_port: "{{ sshd_custom_port }}"
    jump: ACCEPT
  failed_when: false
  notify: save iptables

- name: "Configure SSH {{ sshd_custom_port }} for Ubuntu <= 22.04"
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    backup: true
    owner: "0"
    group: "0"
    mode: "0644"
    validate: /usr/sbin/sshd -T -f %s
  notify: restart sshd
  when: ansible_distribution_version <= "22.04"

- name: "Configure SSH {{ sshd_custom_port }} for Ubuntu == 24.04"
  block:
    - name: Create directory for ssh socket override
      file:
        path: /etc/systemd/system/ssh.socket.d/
        state: directory

    - name: Create SSH socket override configuration
      copy:
        content: |
          [Socket]
          ListenStream=
          ListenStream="{{ sshd_custom_port }}"
        dest: /etc/systemd/system/ssh.socket.d/override.conf
  when: ansible_distribution_version == "24.04"
  notify: daemon-reload
