---
- name: "Allow SSH {{ sshd_custom_port }}"
  iptables:
    action: insert
    chain: INPUT
    protocol: tcp
    destination_port: "{{ sshd_custom_port }}"
    jump: ACCEPT
  failed_when: false
  notify: save iptables

- name: SSHD configuration file update
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    backup: true
    owner: '0'
    group: '0'
    mode: '0644'
    validate: /usr/sbin/sshd -T -f %s
  notify: restart sshd
