---
name: Yamllint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install yamllint
        run: pip install yamllint==1.37.0

      - name: Run yamllint
        run: yamllint . -c .yamllint.yml
